# Lecture 2.0.1: Numpy Random and Random Graphs

![IMDB](l2_hangover.jpg)
Numpy is not only cool because it permits to handle array quite fast (btw, there is C under the hood), but it also have some submodules able to handle a variety of different math things. We are going to learn about random that may be of use for our network analysis.

## Random

[random](https://docs.scipy.org/doc/numpy/reference/routines.random.html) provides a big number of instances for random sampling

In [2]:
import numpy

In [3]:
import numpy.random as random

### Random functions

Random is somehow redundant...<br/>  random.random(size), random.random_sample(size), random.ranf(size), random.sample(size) do exactly the same, i.e. sampling a vector of size size from [0, 1) 

In [4]:
random.random()

0.9351637317070354

In [5]:
random.random(2)

array([0.76665856, 0.03619629])

In [6]:
random.random([2,2])

array([[0.11369501, 0.12058209],
       [0.41602773, 0.56702489]])

random.randint(low, high) instead sample from an interval of integers **[high is exclusive]**

In [7]:
random.randint(0,42)

7

In [8]:
for i in xrange(10):
    if random.randint(0,1)!=0:
        print i

random.choice(array) random choose an element from the array

In [9]:
random.choice(np.arange(42))

15

In [10]:
random.choice(np.arange(42), size=42)

array([33,  3, 34, 31, 24,  0, 17, 26,  2, 26, 18,  3, 23, 37, 11,  2, 41,
        0,  0, 40,  6,  5, 10, 33, 17, 26, 16, 30, 10, 41, 31, 20, 38,  3,
        7, 35, 15, 15, 17, 29, 15,  3])

In [11]:
out=random.choice(np.arange(42), size=42)

In [12]:
len(np.unique(out))==len(out)

False

???

In [13]:
random.choice(np.arange(42), size=42, replace=False)

array([ 9, 33, 36, 12, 16, 30, 39, 34, 10, 37, 25, 22, 18, 19, 27, 41, 20,
        2, 24, 32, 35,  1, 26, 14, 17,  4,  3, 38,  0, 13, 23,  8, 28,  7,
       31, 21, 15, 40,  5, 11, 29,  6])

In [14]:
out=random.choice(np.arange(42), size=42, replace=False)

In [15]:
len(np.unique(out))==len(out)

True

This second feature is analogous to random.permutation()

In [16]:
out=random.permutation(np.arange(42))

In [17]:
len(np.unique(out))==len(out)

True

Instead random.shuffle(something) shuffle someone else 

In [18]:
out=np.arange(42)

In [19]:
out

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41])

In [20]:
random.shuffle(out)

In [21]:
out

array([ 2, 12,  3, 15, 40, 39, 29, 28, 30, 16, 19, 11, 32, 38,  6, 34, 13,
       33, 41,  7, 20, 21, 23, 25, 18,  0, 17, 26, 24,  5, 22, 14,  4,  1,
       10, 37, 31, 36,  8,  9, 27, 35])

### Exercise: generate an instance of a (grand-canonical) Erdös-Renyi random graph for the monopartite network of the previous notebook

In an Erdös-Renyi random graph every link is given a probability equal to the link density, i.e. $p^\text{RG}=\dfrac{2L}{N(N-1)}$. In the grand-canonical approach each possible link is an independent event with probability of success equal to $p_\text{RG} $. Thus, the total number of links is conserved one mean.

#### Load the monopartite adjacency matrix

#### Define the probability per couple of nodes

#### Generate the new adjacency matrix

In principle the number of links is not conserved on a single instance.

### Exercise: generate an instance of a (µ-canonical) Erdös-Renyi random graph for the monopartite network of the previous notebook

Here the solution is to use a trick. random.shuffle is able to reshuffle even matrices, but it does it by reshuffling only rows. 

### Exercise: generate an instance of a (grand-canonical) Configuration Model <br/>(Chung-Lu version) <br/>for the monopartite network of the previous notebook

In a configuration model a la Chung-Lu (better, in the Chung-Lu approximation, from now on CLA), the probability per link is $p^\text{CLA}_{ij}=\dfrac{k_ik_j}{2m}$, where $k_i$ is the degree of the real network of the node $i$. **Exercise in the exercise:** use a piece of paper and a pen to show that the mean degree over the ensemble is equal to the one of the real network.

### Exercise: compare the real $k^\text{nn}$ with the average and $\sigma$ over a sample of 1000 sample with gran-canonical ER and CLA-CM

In order to have the name of the films

In [51]:
bip_el=np.genfromtxt('./data/imdb_2018_films_actors.txt', delimiter='\t', dtype=[('film', 'U50'),('actor', 'U50')])

In [52]:
films, k_films=np.unique(bip_el['film'], return_counts=True)

##### Define a function calculating the $k^\text{nn}$

##### Define a function generating an element of the grand canonical ER

##### Save the $k^\text{nn}$ on the real matrix somewhere

##### Generate a vector of $k^\text{nn}$s vectors, whose elements are the value from the sample of a grand-ER 

By the way, what do I expect about the distribution of the $k^\text{nn}$? Why?

##### CLA-CM sampler

##### Generate a vector of $k^\text{nn}$s vectors, whose elements are the value from the sample of a grand-CLACM

#### Select movies whose k^nn is more significantly more than expected...

#### ...and those whose k^nn is more significantly less than expected.